import React, { Component } from 'react';
import './Skill.scss';

class Skill extends Component {
  render(){
    return (<div>Compétences en cours de développement !</div>)
  }
}

const SkillCategories = {
  dev: {id:"dev", title: "Développement"},
  managment: {id:"managment", title: "Gestion de projet"},
  front: {id:"front",title: "Front"},
  back: {id:"back",title: "Back"},
  langages: {id:"langages",title: "Langages"},
  framework: {id:"framework",title: "Framework"},
};

const Skills = [
  {
    id:1,
    category: SkillCategories.dev,
    subCategory: SkillCategories.front,
    content: "Conception et développement d’interfaces utilisateurs complexes.",
    grade: null,
    years: null,
    linkTo: [10,12,13,14,22,23,20,],
  },
  {
    id:2,
    category: SkillCategories.dev,
    subCategory: SkillCategories.front,
    content: "Connaissances et mise en pratiques de nombreuses bibliothèques (‘framework’) liées aux interfaces utilisateurs.",
    grade: null,
    years: null,
    linkTo: [22,23,20,21,32,],
  },
  {
    id:3,
    category: SkillCategories.dev,
    subCategory: SkillCategories.front,
    content: "Intégration de ‘templates’ de style.",
    grade: null,
    years: null,
    linkTo: [10,12,13,14,22,23,],
  },
  {
    id:4,
    category: SkillCategories.dev,
    subCategory: SkillCategories.back,
    content: "Conception et réalisation d’API web (REST).",
    grade: null,
    years: null,
    linkTo: [7,8,9,15,16,17,19,21,24,25,],
  },
  {
    id:5,
    category: SkillCategories.dev,
    subCategory: SkillCategories.back,
    content: "Connaissances et mise en pratiques de différentes architectures (‘design patterns’) de développement : SOA, MVC, Microservices.",
    grade: null,
    years: null,
    linkTo: [7,8,9,10,17,18,19,], 
  },
  {
    id:6,
    category: SkillCategories.dev,
    subCategory: SkillCategories.back,
    content: "Compréhension et intégrations de Web services externes.",
    grade: null,
    years: null,
    linkTo: [7,10,21,22,], 
  },
  {
    id:7,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "C#",
    grade: 8,
    years: null,
  },
  {
    id:8,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "Java",
    grade: 6,
    years: null, 
  },
  {
    id:9,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "PHP 7",
    grade: 7,
    years: null, 
  },
  {
    id:10,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "Javascript",
    grade: 9,
    years: null, 
  },  
  {
    id:11,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "PowerShell",
    grade: 5,
    years: null,
  },
  {
    id:12,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "HTML 5",
    grade: 6,
    years: null, 
  },
  {
    id:13,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "CSS 3",
    grade: 6,
    years: null, 
  },
  {
    id:14,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "SCSS",
    grade: 6,
    years: null, 
  },
  {
    id:15,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "SQL",
    grade: 8,
    years: null, 
  },  
  {
    id:16,
    category: SkillCategories.dev,
    subCategory: SkillCategories.langages,
    content: "Transact-SQL",
    grade: 7,
    years: null, 
  },
  {
    id:17,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "Symfony 4",
    grade: null,
    years: null, 
  },
  {
    id:18,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "ASP.NET MVC",
    grade: null,
    years: null, 
  },
  {
    id:19,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "ASP.NET Web API",
    grade: null,
    years: null, 
  },
  {
    id:20,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "NodeJS",
    grade: null,
    years: null, 
  },
  {
    id:21,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "SDK Dynamics CRM",
    grade: null,
    years: null, 
  },
  {
    id:22,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "JQuery",
    grade: null,
    years: null, 
  },{
    id:32,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "FullCalendar",
    grade: null,
    years: null, 
  },
  {
    id:23,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "BootStrap",
    grade: null,
    years: null,
  },
  {
    id:24,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "React",
    grade: null,
    years: null, 
  },
  {
    id:25,
    category: SkillCategories.dev,
    subCategory: SkillCategories.framework,
    content: "Spring",
    grade: null,
    years: null, 
  },
  {
    id:33,
    category: SkillCategories.managment,
    subCategory: null,
    content: "Compréhension et assimilation des processus métier",
    grade: null,
    years: null, 
  },
  {
    id:26,
    category: SkillCategories.managment,
    subCategory: null,
    content: "Rédaction de cahier des charges.",
    grade: null,
    years: 5, 
  },
  {
    id:27,
    category: SkillCategories.managment,
    subCategory: null,
    content: "Gestion de projet sous la méthode agile : SCRUM.",
    grade: null,
    years: 4, 
  },
  {
    id:28,
    category: SkillCategories.managment,
    subCategory: null,
    content: "Présentation d’application.",
    grade: null,
    years: 2, 
  },
  {
    id:29,
    category: SkillCategories.managment,
    subCategory: null,
    content: "Animation de réunion utilisateur.",
    grade: null,
    years: 2, 
  },
  {
    id:30,
    category: SkillCategories.managment,
    subCategory: null,
    content: "Management d’une équipe réduite (2 personnes).",
    grade: null,
    years: 1, 
  },
  {
    id:31,
    category: SkillCategories.managment,
    subCategory: null,
    content: "Réalisation d’entretiens.",
    grade: null,
    years: null, 
  },
];

export default Skill;